name: 'Update Contributors List'

on:
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * 0

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  add-contributors:
    name: 'Add Contributors'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Update CONTRIBUTORS.md'
        uses: akhilmhdh/contributors-readme-action@v2.3.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          readme_path: CONTRIBUTORS.md
          collaborators: all
          use_username: true
          commit_message: 'docs: updated `CONTRIBUTORS.md`'
          committer_username: github-actions[bot]
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          pr_title_on_protected: 'docs: update `CONTRIBUTORS.md`'
          auto_detect_branch_protection: true
